# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Wtp/Desktop/UTCN/An 2/Semestru 2/CA/project_1a/project_1.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Wtp/Desktop/UTCN/An 2/Semestru 2/CA/project_1a/project_1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Wtp/Desktop/UTCN/An 2/Semestru 2/CA/project_1a/project_1.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Wtp/Desktop/UTCN/An 2/Semestru 2/CA/project_1a/project_1.srcs/sources_1/new/seg7.vhd}
  {C:/Users/Wtp/Desktop/UTCN/An 2/Semestru 2/CA/project_1a/project_1.srcs/sources_1/new/mps.vhd}
  {C:/Users/Wtp/Desktop/UTCN/An 2/Semestru 2/CA/project_1a/project_1.srcs/sources_1/new/test_env1.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Wtp/Desktop/UTCN/An 2/Semestru 2/CA/project_1a/basys3.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Wtp/Desktop/UTCN/An 2/Semestru 2/CA/project_1a/basys3.xdc}}]


synth_design -top proj1_test -part xc7a35tcpg236-1


write_checkpoint -force -noxdef proj1_test.dcp

catch { report_utilization -file proj1_test_utilization_synth.rpt -pb proj1_test_utilization_synth.pb }
